name: super_text_layout
description: Configurable, composable, extensible text display for Flutter.
version: 0.1.3
homepage: https://github.com/superlistapp/super_editor
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  attributed_text:
    git:
      url: https://github.com/hieupham-anfin/attributed_text.git
      path: attributed_text
  logging: ^1.0.1
